### ISSUE TITLE
Device ID with name

### ISSUE THREAD

**Issue by poudenes** [galinette2000/espmilighthub-domoticz#11]
Hi,

Sidoh will implement device names. 

https://github.com/sidoh/esp8266_milight_hub/pull/481

Maybe you can update also your plugin so when people have add Device names, that name will be used when they added to Domoticz?

You create all your lights in the Hub with right names, and only what you do is add them in domoticz and the names are already there ... 

Cheers

**Comment by csigabit** [comment]
Hi!
I wanted to suggest exactly the same.
Keep on with the good work and thanks for the plugin!
Bests

**Comment by csigabit** [comment]
Workaround:
- Remove existing hardware in domoticz, I also deleted the cache file from the plugin directory

- Stop domoticz

- Modify plugin:
	Name = str(device_id)+'/'+str(device_type)+'/'+str(group_id)
		to
	Name = str(device_id)

- Set Device Name in the hub for all used Groups in all used Device Ids

- MQTT settings in the hub:
	MQTT topic pattern
	milight/:device_alias/:device_type/:group_id
	MQTT update topic pattern
	milight/updates/:device_alias/:device_type/:group_id
	MQTT state topic pattern
	milight/states/:device_alias/:device_type/:group_id
	Group state fields
	All

- Start domoticz

- Add plugin to domoticz with Name: "Lamp"! The created devicenames will start with "Lamp - " then

- MQTT settings in the domoticz plugin:
	mqtt_topic_pattern
	milight/:device_id/:device_type/:group_id
	mqtt_states_topic_pattern
	milight/states/:device_id/:device_type/:group_id
	mqtt_updates_topic_pattern
	milight/updates/:device_id/:device_type/:group_id
