### ISSUE TITLE
Group 0

### ISSUE THREAD

**Issue by poudenes** [galinette2000/espmilighthub-domoticz#7]
Hi,

When I turn on and off group 0 all other groups keep their status.
Is this a normal behaviour? My idea when I turn on/off group 0 all other groups 1 2 3 4 will get this status.

**Comment by etsach** [comment]
Have you been to the Hardware setup in Domoticz to set the new "updates"
MQTT topic? If not set, they will not update.

**Comment by etsach** [comment]
Also, there is a lag of a few seconds before update, because I wait for the
hub MQTT response for updating.

**Comment by poudenes** [comment]
> Have you been to the Hardware setup in Domoticz to set the new "updates" MQTT topic? If not set, they will not update. Le mer. 29 mai 2019 à 10:15, poudenes <notifications@github.com> a écrit :
> […](#)

You mean the new updates with MQTT Pattern?

mqtt_topic_pattern: milight/:device_id/:device_type/:group_id
mqtt_state_topic_pattern: milight/states/:hex_device_id/:device_type/:group_id

Only Group 0 is turning on/off (act like a normal group)
(Im using 1.9.0 Firmware on the hub)

**Comment by etsach** [comment]
There is a new, third MQTT pattern parameter in v0.0.9, with "updates"
instead of "states" (as in hub MQTT settings), it is necessary for updating
bulbs from group ALL.

**Comment by poudenes** [comment]
But in your plugin there are 2 lines for MQTT:

This is how I setup both

**Hub MQTT settings**
MQTT topic pattern: milight/:device_id/:device_type/:group_id
MQTT update topic pattern: milight/updates/:hex_device_id/:device_type/:group_id
MQTT state topic pattern: milight/states/:hex_device_id/:device_type/:group_id

**Plugin settings**
MQTT topic pattern: milight/:device_id/:device_type/:group_id
MQTT state topic pattern: milight/states/:hex_device_id/:device_type/:group_id
MQTT update topic pattern: **(NOT AVAILABLE)**

**Comment by poudenes** [comment]
Issue solved. Update the plugin to 0.0.9 :D
